apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rego-adventure
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - rego.mydomain.local
      secretName: rego-tls
  rules:
    - host: rego.mydomain.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rego-adventure
                port:
                  number: 80